variables:
  DISTRIBUTION_VER: "buster"

image: docker.git.sos.ethz.ch/isg/debian-ci-base:$DISTRIBUTION_VER

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - apt update
    - apt install -y --no-install-recommends python3-certbot python3 python3-setuptools python3-grpcio dh-python
  script:
    - dpkg-buildpackage -b -us -uc
    - mkdir debbuild
    - mv ../*.deb debbuild/
  artifacts:
    paths:
    - debbuild/*

deploy_to_apt:
  stage: deploy
  script:
    - echo "Deploying package to $CI_APT_PREFIX prefix and $DISTRIBUTION_VER version"
    - sudo -u repo aptly repo add $CI_APT_REPO debbuild/*.deb
    - sudo -u repo aptly publish update $DISTRIBUTION_VER $CI_APT_PREFIX
  only:
    - tags
  tags:
    - apt
