# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import certbot_dns_eth_api.dnsapi_pb2 as dnsapi__pb2


class DnsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateARecord = channel.unary_unary(
        '/Dns/CreateARecord',
        request_serializer=dnsapi__pb2.CreateARecordRequest.SerializeToString,
        response_deserializer=dnsapi__pb2.EmptyResponse.FromString,
        )
    self.DeleteARecord = channel.unary_unary(
        '/Dns/DeleteARecord',
        request_serializer=dnsapi__pb2.DeleteARecordRequest.SerializeToString,
        response_deserializer=dnsapi__pb2.EmptyResponse.FromString,
        )
    self.CreateCNameRecord = channel.unary_unary(
        '/Dns/CreateCNameRecord',
        request_serializer=dnsapi__pb2.CreateCNameRecordRequest.SerializeToString,
        response_deserializer=dnsapi__pb2.EmptyResponse.FromString,
        )
    self.DeleteCNameRecord = channel.unary_unary(
        '/Dns/DeleteCNameRecord',
        request_serializer=dnsapi__pb2.DeleteCNameRecordRequest.SerializeToString,
        response_deserializer=dnsapi__pb2.EmptyResponse.FromString,
        )
    self.CreateTxtRecord = channel.unary_unary(
        '/Dns/CreateTxtRecord',
        request_serializer=dnsapi__pb2.CreateTxtRecordRequest.SerializeToString,
        response_deserializer=dnsapi__pb2.EmptyResponse.FromString,
        )
    self.SearchTxtRecord = channel.unary_unary(
        '/Dns/SearchTxtRecord',
        request_serializer=dnsapi__pb2.SearchTxtRecordRequest.SerializeToString,
        response_deserializer=dnsapi__pb2.TxtResponse.FromString,
        )
    self.DeleteTxtRecord = channel.unary_unary(
        '/Dns/DeleteTxtRecord',
        request_serializer=dnsapi__pb2.DeleteTxtRecordRequest.SerializeToString,
        response_deserializer=dnsapi__pb2.EmptyResponse.FromString,
        )


class DnsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateARecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteARecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateCNameRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteCNameRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateTxtRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SearchTxtRecord(self, request, context):
    """Does not return information about the ISG group the record belongs to, because why not.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTxtRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DnsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateARecord': grpc.unary_unary_rpc_method_handler(
          servicer.CreateARecord,
          request_deserializer=dnsapi__pb2.CreateARecordRequest.FromString,
          response_serializer=dnsapi__pb2.EmptyResponse.SerializeToString,
      ),
      'DeleteARecord': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteARecord,
          request_deserializer=dnsapi__pb2.DeleteARecordRequest.FromString,
          response_serializer=dnsapi__pb2.EmptyResponse.SerializeToString,
      ),
      'CreateCNameRecord': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCNameRecord,
          request_deserializer=dnsapi__pb2.CreateCNameRecordRequest.FromString,
          response_serializer=dnsapi__pb2.EmptyResponse.SerializeToString,
      ),
      'DeleteCNameRecord': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteCNameRecord,
          request_deserializer=dnsapi__pb2.DeleteCNameRecordRequest.FromString,
          response_serializer=dnsapi__pb2.EmptyResponse.SerializeToString,
      ),
      'CreateTxtRecord': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTxtRecord,
          request_deserializer=dnsapi__pb2.CreateTxtRecordRequest.FromString,
          response_serializer=dnsapi__pb2.EmptyResponse.SerializeToString,
      ),
      'SearchTxtRecord': grpc.unary_unary_rpc_method_handler(
          servicer.SearchTxtRecord,
          request_deserializer=dnsapi__pb2.SearchTxtRecordRequest.FromString,
          response_serializer=dnsapi__pb2.TxtResponse.SerializeToString,
      ),
      'DeleteTxtRecord': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTxtRecord,
          request_deserializer=dnsapi__pb2.DeleteTxtRecordRequest.FromString,
          response_serializer=dnsapi__pb2.EmptyResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Dns', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
