# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dnsapi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dnsapi.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\027ch.ethz.vis.dnsapi.grpc'),
  serialized_pb=_b('\n\x0c\x64nsapi.proto\"J\n\rRecordOptions\x12\x0b\n\x03ttl\x18\x01 \x01(\r\x12\x10\n\x08isgGroup\x18\x02 \x01(\t\x12\x1a\n\x12\x65xternallyViewable\x18\x03 \x01(\x08\"f\n\x14\x43reateARecordRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0e\n\x06ipName\x18\x02 \x01(\t\x12\x11\n\tsubdomain\x18\x03 \x01(\t\x12\x1f\n\x07options\x18\n \x01(\x0b\x32\x0e.RecordOptions\"4\n\x14\x44\x65leteARecordRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\"s\n\x18\x43reateCNameRecordRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x11\n\taliasName\x18\x02 \x01(\t\x12\x11\n\tsubdomain\x18\x03 \x01(\t\x12\x1f\n\x07options\x18\n \x01(\x0b\x32\x0e.RecordOptions\")\n\x18\x44\x65leteCNameRecordRequest\x12\r\n\x05\x61lias\x18\x01 \x01(\t\"l\n\x16\x43reateTxtRecordRequest\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0f\n\x07txtName\x18\x02 \x01(\t\x12\x11\n\tsubdomain\x18\x03 \x01(\t\x12\x1f\n\x07options\x18\n \x01(\x0b\x32\x0e.RecordOptions\"(\n\x16SearchTxtRecordRequest\x12\x0e\n\x06\x66qName\x18\x01 \x01(\t\"7\n\x16\x44\x65leteTxtRecordRequest\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06\x66qName\x18\x02 \x01(\t\"\x0f\n\rEmptyResponse\"M\n\x0bTxtResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06\x66qName\x18\x02 \x01(\t\x12\x1f\n\x07options\x18\x03 \x01(\x0b\x32\x0e.RecordOptions2\xa7\x03\n\x03\x44ns\x12\x36\n\rCreateARecord\x12\x15.CreateARecordRequest\x1a\x0e.EmptyResponse\x12\x36\n\rDeleteARecord\x12\x15.DeleteARecordRequest\x1a\x0e.EmptyResponse\x12>\n\x11\x43reateCNameRecord\x12\x19.CreateCNameRecordRequest\x1a\x0e.EmptyResponse\x12>\n\x11\x44\x65leteCNameRecord\x12\x19.DeleteCNameRecordRequest\x1a\x0e.EmptyResponse\x12:\n\x0f\x43reateTxtRecord\x12\x17.CreateTxtRecordRequest\x1a\x0e.EmptyResponse\x12\x38\n\x0fSearchTxtRecord\x12\x17.SearchTxtRecordRequest\x1a\x0c.TxtResponse\x12:\n\x0f\x44\x65leteTxtRecord\x12\x17.DeleteTxtRecordRequest\x1a\x0e.EmptyResponseB\x19\n\x17\x63h.ethz.vis.dnsapi.grpcb\x06proto3')
)




_RECORDOPTIONS = _descriptor.Descriptor(
  name='RecordOptions',
  full_name='RecordOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ttl', full_name='RecordOptions.ttl', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isgGroup', full_name='RecordOptions.isgGroup', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='externallyViewable', full_name='RecordOptions.externallyViewable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=90,
)


_CREATEARECORDREQUEST = _descriptor.Descriptor(
  name='CreateARecordRequest',
  full_name='CreateARecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='CreateARecordRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipName', full_name='CreateARecordRequest.ipName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subdomain', full_name='CreateARecordRequest.subdomain', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='CreateARecordRequest.options', index=3,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=194,
)


_DELETEARECORDREQUEST = _descriptor.Descriptor(
  name='DeleteARecordRequest',
  full_name='DeleteARecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='DeleteARecordRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='DeleteARecordRequest.hostname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=248,
)


_CREATECNAMERECORDREQUEST = _descriptor.Descriptor(
  name='CreateCNameRecordRequest',
  full_name='CreateCNameRecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='CreateCNameRecordRequest.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aliasName', full_name='CreateCNameRecordRequest.aliasName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subdomain', full_name='CreateCNameRecordRequest.subdomain', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='CreateCNameRecordRequest.options', index=3,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=365,
)


_DELETECNAMERECORDREQUEST = _descriptor.Descriptor(
  name='DeleteCNameRecordRequest',
  full_name='DeleteCNameRecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alias', full_name='DeleteCNameRecordRequest.alias', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=408,
)


_CREATETXTRECORDREQUEST = _descriptor.Descriptor(
  name='CreateTxtRecordRequest',
  full_name='CreateTxtRecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='CreateTxtRecordRequest.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='txtName', full_name='CreateTxtRecordRequest.txtName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subdomain', full_name='CreateTxtRecordRequest.subdomain', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='CreateTxtRecordRequest.options', index=3,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=518,
)


_SEARCHTXTRECORDREQUEST = _descriptor.Descriptor(
  name='SearchTxtRecordRequest',
  full_name='SearchTxtRecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fqName', full_name='SearchTxtRecordRequest.fqName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=560,
)


_DELETETXTRECORDREQUEST = _descriptor.Descriptor(
  name='DeleteTxtRecordRequest',
  full_name='DeleteTxtRecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='DeleteTxtRecordRequest.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fqName', full_name='DeleteTxtRecordRequest.fqName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=617,
)


_EMPTYRESPONSE = _descriptor.Descriptor(
  name='EmptyResponse',
  full_name='EmptyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=619,
  serialized_end=634,
)


_TXTRESPONSE = _descriptor.Descriptor(
  name='TxtResponse',
  full_name='TxtResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='TxtResponse.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fqName', full_name='TxtResponse.fqName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='TxtResponse.options', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=636,
  serialized_end=713,
)

_CREATEARECORDREQUEST.fields_by_name['options'].message_type = _RECORDOPTIONS
_CREATECNAMERECORDREQUEST.fields_by_name['options'].message_type = _RECORDOPTIONS
_CREATETXTRECORDREQUEST.fields_by_name['options'].message_type = _RECORDOPTIONS
_TXTRESPONSE.fields_by_name['options'].message_type = _RECORDOPTIONS
DESCRIPTOR.message_types_by_name['RecordOptions'] = _RECORDOPTIONS
DESCRIPTOR.message_types_by_name['CreateARecordRequest'] = _CREATEARECORDREQUEST
DESCRIPTOR.message_types_by_name['DeleteARecordRequest'] = _DELETEARECORDREQUEST
DESCRIPTOR.message_types_by_name['CreateCNameRecordRequest'] = _CREATECNAMERECORDREQUEST
DESCRIPTOR.message_types_by_name['DeleteCNameRecordRequest'] = _DELETECNAMERECORDREQUEST
DESCRIPTOR.message_types_by_name['CreateTxtRecordRequest'] = _CREATETXTRECORDREQUEST
DESCRIPTOR.message_types_by_name['SearchTxtRecordRequest'] = _SEARCHTXTRECORDREQUEST
DESCRIPTOR.message_types_by_name['DeleteTxtRecordRequest'] = _DELETETXTRECORDREQUEST
DESCRIPTOR.message_types_by_name['EmptyResponse'] = _EMPTYRESPONSE
DESCRIPTOR.message_types_by_name['TxtResponse'] = _TXTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecordOptions = _reflection.GeneratedProtocolMessageType('RecordOptions', (_message.Message,), {
  'DESCRIPTOR' : _RECORDOPTIONS,
  '__module__' : 'dnsapi_pb2'
  # @@protoc_insertion_point(class_scope:RecordOptions)
  })
_sym_db.RegisterMessage(RecordOptions)

CreateARecordRequest = _reflection.GeneratedProtocolMessageType('CreateARecordRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEARECORDREQUEST,
  '__module__' : 'dnsapi_pb2'
  # @@protoc_insertion_point(class_scope:CreateARecordRequest)
  })
_sym_db.RegisterMessage(CreateARecordRequest)

DeleteARecordRequest = _reflection.GeneratedProtocolMessageType('DeleteARecordRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEARECORDREQUEST,
  '__module__' : 'dnsapi_pb2'
  # @@protoc_insertion_point(class_scope:DeleteARecordRequest)
  })
_sym_db.RegisterMessage(DeleteARecordRequest)

CreateCNameRecordRequest = _reflection.GeneratedProtocolMessageType('CreateCNameRecordRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATECNAMERECORDREQUEST,
  '__module__' : 'dnsapi_pb2'
  # @@protoc_insertion_point(class_scope:CreateCNameRecordRequest)
  })
_sym_db.RegisterMessage(CreateCNameRecordRequest)

DeleteCNameRecordRequest = _reflection.GeneratedProtocolMessageType('DeleteCNameRecordRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETECNAMERECORDREQUEST,
  '__module__' : 'dnsapi_pb2'
  # @@protoc_insertion_point(class_scope:DeleteCNameRecordRequest)
  })
_sym_db.RegisterMessage(DeleteCNameRecordRequest)

CreateTxtRecordRequest = _reflection.GeneratedProtocolMessageType('CreateTxtRecordRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATETXTRECORDREQUEST,
  '__module__' : 'dnsapi_pb2'
  # @@protoc_insertion_point(class_scope:CreateTxtRecordRequest)
  })
_sym_db.RegisterMessage(CreateTxtRecordRequest)

SearchTxtRecordRequest = _reflection.GeneratedProtocolMessageType('SearchTxtRecordRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHTXTRECORDREQUEST,
  '__module__' : 'dnsapi_pb2'
  # @@protoc_insertion_point(class_scope:SearchTxtRecordRequest)
  })
_sym_db.RegisterMessage(SearchTxtRecordRequest)

DeleteTxtRecordRequest = _reflection.GeneratedProtocolMessageType('DeleteTxtRecordRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETETXTRECORDREQUEST,
  '__module__' : 'dnsapi_pb2'
  # @@protoc_insertion_point(class_scope:DeleteTxtRecordRequest)
  })
_sym_db.RegisterMessage(DeleteTxtRecordRequest)

EmptyResponse = _reflection.GeneratedProtocolMessageType('EmptyResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYRESPONSE,
  '__module__' : 'dnsapi_pb2'
  # @@protoc_insertion_point(class_scope:EmptyResponse)
  })
_sym_db.RegisterMessage(EmptyResponse)

TxtResponse = _reflection.GeneratedProtocolMessageType('TxtResponse', (_message.Message,), {
  'DESCRIPTOR' : _TXTRESPONSE,
  '__module__' : 'dnsapi_pb2'
  # @@protoc_insertion_point(class_scope:TxtResponse)
  })
_sym_db.RegisterMessage(TxtResponse)


DESCRIPTOR._options = None

_DNS = _descriptor.ServiceDescriptor(
  name='Dns',
  full_name='Dns',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=716,
  serialized_end=1139,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateARecord',
    full_name='Dns.CreateARecord',
    index=0,
    containing_service=None,
    input_type=_CREATEARECORDREQUEST,
    output_type=_EMPTYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteARecord',
    full_name='Dns.DeleteARecord',
    index=1,
    containing_service=None,
    input_type=_DELETEARECORDREQUEST,
    output_type=_EMPTYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateCNameRecord',
    full_name='Dns.CreateCNameRecord',
    index=2,
    containing_service=None,
    input_type=_CREATECNAMERECORDREQUEST,
    output_type=_EMPTYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteCNameRecord',
    full_name='Dns.DeleteCNameRecord',
    index=3,
    containing_service=None,
    input_type=_DELETECNAMERECORDREQUEST,
    output_type=_EMPTYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateTxtRecord',
    full_name='Dns.CreateTxtRecord',
    index=4,
    containing_service=None,
    input_type=_CREATETXTRECORDREQUEST,
    output_type=_EMPTYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SearchTxtRecord',
    full_name='Dns.SearchTxtRecord',
    index=5,
    containing_service=None,
    input_type=_SEARCHTXTRECORDREQUEST,
    output_type=_TXTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteTxtRecord',
    full_name='Dns.DeleteTxtRecord',
    index=6,
    containing_service=None,
    input_type=_DELETETXTRECORDREQUEST,
    output_type=_EMPTYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DNS)

DESCRIPTOR.services_by_name['Dns'] = _DNS

# @@protoc_insertion_point(module_scope)
